global:
  scrape_interval:     15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['172.26.208.1:9090']
  - job_name: 'cadvisor'
    static_configs:
    - targets: ['172.26.208.1:8899']
  - job_name: 'node'
    static_configs:
    - targets: ['172.26.208.1:9100']
  - job_name: 'flink'
    static_configs:
      - targets: ['172.26.209.23:9020']
        labels:
          group: jm
      - targets: ['172.26.209.23:9021']
        labels:
          group: tm